---
language: ruby
sudo: false
cache: bundler
bundler_args: --without yard benchmarks
script: "bundle exec rake ci"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - rbx-2
  - jruby-9000
  - jruby-head
  - ruby-head
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  include:
    - rvm: jruby-19mode
    - rvm: jruby-20mode
    - rvm: jruby-21mode
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
branches:
  only: master
