---
language: ruby
sudo: false
cache: bundler
script: "bundle exec rake ci"
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9000
  - jruby-head
  - rbx-3
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9000
    - rvm: rbx-3
  fast_finish: true
branches:
  only: master
notifications:
  email: false
