---
language: ruby
sudo: false
cache: bundler
bundler_args: --without yard benchmarks
script: "bundle exec rake ci"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby-19mode
  - jruby
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
branches:
  only: master
